name: Rust

on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Debug Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generating Dockerfile from Modusfile
      run: target/debug/modus transpile Modusfile 'all("frontend", "release")' > /tmp/modus-frontend.Dockerfile && cat /tmp/modus-frontend.Dockerfile
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker build frontend
      if: github.event_name != 'pull_request'
      run: >
        SHORT_SHA=$(echo $GITHUB_SHA | head -c 10) &&
        IMAGE_BASE=ghcr.io/$GITHUB_REPOSITORY-buildkit-frontend &&
        IMAGE_REF=$IMAGE_BASE:$SHORT_SHA &&
        export MODUS_EXECUTABLE=$PWD/target/debug/modus MODUS_BUILDKIT_FRONTEND=$IMAGE_REF &&
        cd test && python -m unittest discover && cd .. &&
        docker build -t $IMAGE_REF -f /tmp/modus-frontend.Dockerfile . &&
        docker tag $IMAGE_REF $IMAGE_BASE:latest &&
        docker push $IMAGE_REF &&
        docker push $IMAGE_BASE:latest
